# Build vim from source with python3 support and execute tests.
branches:
  only:
    - travis

before_install:
    # Change the default shell for makefiles.
    - export SHELL=/bin/bash

    # Change from dash to bash.
    - sudo rm /bin/sh
    - sudo ln -s /bin/bash /bin/sh

    # Reinstall pip3 otherwise will get errors.
    - sudo apt-get remove python3-pip
    - sudo apt-get install python3-pip

    - sudo apt install python3-dev

    # Get rid of 'double free or corruption' error.
    - sudo apt-get install libtcmalloc-minimal4
    - export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"

before_script:
    # Start X interface.
    - export DISPLAY=:0.0
    - "sh -e /etc/init.d/xvfb start"
    - sleep 5 # give xvfb some time to start

install: SHELL=/bin/bash make install
script: SHELL=/bin/bash make run
